xml version=1.0 encoding=utf-8
Project DefaultTargets=Build xmlns=httpschemas.microsoft.comdevelopermsbuild2003

  ItemGroup Label=ProjectConfigurations
    ProjectConfiguration Include=Debugx64
      ConfigurationDebugConfiguration
      Platformx64Platform
    ProjectConfiguration
    ProjectConfiguration Include=Releasex64
      ConfigurationReleaseConfiguration
      Platformx64Platform
    ProjectConfiguration
  ItemGroup

  PropertyGroup Label=Globals
    ProjectGuid{12345678-ABCD-1234-ABCD-1234567890AB}ProjectGuid
    KeywordQtVS_v304Keyword
    QtMsBuild Condition='$(QtMsBuild)'==''$(MSBuildProjectDirectory)QtMsBuildQtMsBuild
    WindowsTargetPlatformVersion10.0WindowsTargetPlatformVersion
  PropertyGroup

  Import Project=$(VCTargetsPath)Microsoft.Cpp.Default.props 

  PropertyGroup Condition='$(Configuration)$(Platform)'=='Debugx64' Label=Configuration
    ConfigurationTypeApplicationConfigurationType
    UseDebugLibrariestrueUseDebugLibraries
    PlatformToolsetv143PlatformToolset
  PropertyGroup

  PropertyGroup Condition='$(Configuration)$(Platform)'=='Releasex64' Label=Configuration
    ConfigurationTypeApplicationConfigurationType
    UseDebugLibrariesfalseUseDebugLibraries
    PlatformToolsetv143PlatformToolset
  PropertyGroup

  Import Project=$(VCTargetsPath)Microsoft.Cpp.props 

  !-- Qt yolunu buraya ekle --
  PropertyGroup Label=QtSettings
    QtInstall6.7.2msvc2019_64QtInstall
    QtModulescore;gui;widgetsQtModules
  PropertyGroup

  ItemGroup
    ClCompile Include=main.cpp 
    ClCompile Include=MainWindow.cpp 
  ItemGroup

  ItemGroup
    ClInclude Include=MainWindow.h 
  ItemGroup

  ItemGroup
    QtUic Include=PetekA.ui 
  ItemGroup

  Import Project=$(QtMsBuild)qt.targets 

  Import Project=$(VCTargetsPath)Microsoft.Cpp.targets 
Project
